spring.application.name=dns-server
ns.domain.servers=114.114.114.114,8.8.8.8
spring.redis.host=192.168.10.201
spring.redis.port=6379
#dns.server.ip=127.0.0.1
dns.server.name=fuled.public.dns
dns.query.cache.fixed.ttl=3600
spring.data.elasticsearch.repositories.enabled=true
spring.elasticsearch.rest.uris=http://192.168.10.201:9200

bean.explorer.enabled=true
bean.explorer.page-path=/bean-explorer.html
bean.explorer.api-path=/bean-explorer/api
bean.explorer.auth.enabled=true
bean.explorer.auth.token=dnsserver
bean.explorer.auth.header-name=X-Bean-Explorer-Token
bean.explorer.auth.query-param=token


#dns.persist.test=#{${test.key:}==''? 'a':'b'}
#dns.persist.test=#{systemProperties['os.name']}
